### ISSUE TITLE
Data Consistency

### ISSUE THREAD

**Issue by ccubed** [viion/XIVDB-API#4]
Okay,

I've been using this API since the original version of the xivdb website and Data Consistency is absolutely the worst issue you have. It makes working with your API a nightmare. For the latest example of Data Inconsistency, what used to url_xivdb is now simply url. That attribute was an absolute url but is now simply a relative url. So maybe, I thought, the fault lies with me not paying attention to your dev notes. However, no, you don't list this change anywhere that I can find. The last dev post on the website is about better locations. 

Can we please either get a place where you announce these changes ahead of time or can we make the data more consistent going forward?

Thanks.

**Comment by viion** [comment]
The API is not officially launched yet, expect things like this. xivdb_url was removed because it was part of my multi-language code that included all language. Having all languages in a search response causes massive amount of data response so I took it out. 

Honestly, I care about making the API responsive and not using a ton of resources before consistency, theres no staple 1.0 scheme I have laid out.

It was also posted in: http://xivdb.com/devblog?id=19

```
Language-specific URLs and Names have been removed from search results
The search result data is getting far too big and taking a long time to process.
```

Not the best place I agree and having a central place (the idea is this repo will be that) would be the place. 

But like I said, it's not officially ready yet.

For the sake of this specific argument, `xivdb_url` should be included in search results, it got ommited due to its ties to the language url generation. I need to include it in and exclude the others.

**Comment by viion** [comment]
I've fixed the specific issue you had

```
"url": "\/item\/17717\/inspector's+eyeglasses",
"url_api": "https:\/\/api.xivdb.com\/item\/17717",
"url_type": "item",
"url_xivdb": "http:\/\/xivdb.com\/item\/17717\/inspector's+eyeglasses"
```

If there are more, please make issues. There will be major inconsistencies with some data that seems similar (desc_en or help_en or text_en), this is mostly due to inconsistencies within the data files (Mounts have a lot of this...) and these will likely be changed at some point.

**Comment by ccubed** [comment]
A central place for specific changes would be nice. Thanks for adding it back in.
